language: ruby

rvm:
  - 1.8.7
  - 1.9.3

script:
  - rake spec
  - rake lint

env:
  - PUPPET_VERSION="2.7.0"
  - PUPPET_VERSION="3.0.0"
  - PUPPET_VERSION="3.2.0"
  - PUPPET_VERSION="3.4.0"
  - PUPPET_VERSION="3.6.0"

gemfile: .gemfile
