language: ruby

rvm:
  - 1.8.7
  - 1.9.3

script:
  - rake spec
  - rake lint

env:
  - PUPPET_VERSION="2.7"
  - PUPPET_VERSION="3.0"
  - PUPPET_VERSION="3.2"
  - PUPPET_VERSION="3.4"
  - PUPPET_VERSION="3.6"

gemfile: .gemfile
